require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const slugify = require('slugify');
const Category = require('./models/Category');
const Product = require('./models/Product');
const Coupon = require('./models/Coupon');
const User = require('./models/User');

const connectDB = async () => {
  try {
    const conn = await mongoose.connect(process.env.MONGO_URI, {
      serverSelectionTimeoutMS: 10000,
      socketTimeoutMS: 45000,
    });
    console.log(`✅ MongoDB Connected: ${conn.connection.host}`);
    return conn;
  } catch (error) {
    console.error('❌ MongoDB connection failed:', error);
    process.exit(1);
  }
};

const seedCategories = async () => {
  const categories = [
    { name: 'Herbal Tea', description: 'Natural and organic herbal teas for wellness and relaxation.', isActive: true, sortOrder: 1 },
    { name: 'Coffee', description: 'Premium quality coffee beans and powders sourced directly from growers.', isActive: true, sortOrder: 2 },
    { name: 'Pepper', description: 'Finest black, white, and specialty peppercorns from India.', isActive: true, sortOrder: 3 },
    { name: 'Spices', description: 'Authentic aromatic spices for your kitchen.', isActive: true, sortOrder: 4 },
    { name: 'Honey', description: 'Pure, raw, and organic honey varieties from trusted apiaries.', isActive: true, sortOrder: 5 },
  ];

  for (const cat of categories) {
    const existing = await Category.findOne({ name: cat.name });
    if (!existing) {
      await Category.create(cat);
      console.log(`  ✓ Category created: ${cat.name}`);
    } else {
      console.log(`  - Category exists: ${cat.name}`);
    }
  }

  return await Category.find({}).sort({ sortOrder: 1 });
};

const seedProducts = async (categories) => {
  const products = [
    // Herbal Tea
    {
      name: 'Organic Chamomile Tea',
      description: 'Pure organic chamomile flowers dried to perfection. This soothing caffeine-free tea helps with relaxation, improves sleep quality, and supports digestive health. Made from 100% natural chamomile blossoms.',
      shortDescription: 'Soothing caffeine-free tea for relaxation and better sleep.',
      categoryName: 'Herbal Tea',
      price: 299,
      comparePrice: 499,
      costPrice: 180,
      sku: 'BLM-HRT-001',
      stock: 100,
      lowStockThreshold: 15,
      images: [{ public_id: 'seed/herbal-tea/chamomile', url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=500&auto=format&fit=crop&q=60' }],
      weight: 100,
      unit: 'g',
      tags: ['organic', 'caffeine-free', 'sleep', 'relaxation'],
      isFeatured: true,
      isActive: true,
      isOrganic: true,
      ratings: 4.8,
      numReviews: 124,
      soldCount: 450,
      metaTitle: 'Organic Chamomile Tea - BloomHerbs',
      metaDescription: 'Buy premium organic chamomile tea for relaxation and better sleep at BloomHerbs.',
    },
    {
      name: 'Green Tea Matcha Powder',
      description: 'Ceremonial grade Japanese matcha powder rich in antioxidants. Perfect for lattes, smoothies, and baking. Stone-ground from shade-grown green tea leaves for maximum nutritional benefits.',
      shortDescription: 'Ceremonial grade matcha powder rich in antioxidants.',
      categoryName: 'Herbal Tea',
      price: 599,
      comparePrice: 799,
      costPrice: 380,
      sku: 'BLM-HRT-002',
      stock: 75,
      lowStockThreshold: 10,
      images: [{ public_id: 'seed/herbal-tea/matcha', url: 'https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?w=500&auto=format&fit=crop&q=60' }],
      weight: 50,
      unit: 'g',
      tags: ['matcha', 'antioxidants', 'japanese', 'premium'],
      isFeatured: true,
      isActive: true,
      isOrganic: true,
      ratings: 4.7,
      numReviews: 89,
      soldCount: 320,
      metaTitle: 'Green Tea Matcha Powder - BloomHerbs',
      metaDescription: 'Premium ceremonial grade matcha powder for healthy living.',
    },
    {
      name: 'Peppermint Tea Bags',
      description: 'Refreshing peppermint tea in convenient tea bags. Made from pure peppermint leaves grown in the Himalayan foothills. Great for digestion, fresh breath, and natural energy boost.',
      shortDescription: 'Refreshing peppermint tea bags for digestion and freshness.',
      categoryName: 'Herbal Tea',
      price: 249,
      comparePrice: 349,
      costPrice: 140,
      sku: 'BLM-HRT-003',
      stock: 120,
      lowStockThreshold: 20,
      images: [{ public_id: 'seed/herbal-tea/peppermint', url: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=500&auto=format&fit=crop&q=60' }],
      weight: 20,
      unit: 'pcs',
      tags: ['peppermint', 'digestive', 'refreshing', 'bags'],
      isFeatured: false,
      isActive: true,
      isOrganic: true,
      ratings: 4.5,
      numReviews: 67,
      soldCount: 280,
      metaTitle: 'Peppermint Tea Bags - BloomHerbs',
      metaDescription: 'Natural peppermint tea bags for a refreshing and healthy experience.',
    },
    {
      name: 'Hibiscus Flower Tea',
      description: 'Vibrant and tangy hibiscus tea made from dried calyces. Rich in vitamin C and antioxidants. Naturally caffeine-free with a beautiful crimson color and tart cranberry-like flavor.',
      shortDescription: 'Tangy caffeine-free hibiscus tea rich in vitamin C.',
      categoryName: 'Herbal Tea',
      price: 279,
      comparePrice: 399,
      costPrice: 160,
      sku: 'BLM-HRT-004',
      stock: 90,
      lowStockThreshold: 15,
      images: [{ public_id: 'seed/herbal-tea/hibiscus', url: 'https://images.unsplash.com/photo-1563822249366-3efb23b8e0c9?w=500&auto=format&fit=crop&q=60' }],
      weight: 80,
      unit: 'g',
      tags: ['hibiscus', 'vitamin-c', 'caffeine-free', 'antioxidants'],
      isFeatured: false,
      isActive: true,
      isOrganic: true,
      ratings: 4.6,
      numReviews: 52,
      soldCount: 190,
      metaTitle: 'Hibiscus Flower Tea - BloomHerbs',
      metaDescription: 'Tangy hibiscus flower tea naturally rich in antioxidants and vitamin C.',
    },
    {
      name: 'Lemongrass Ginger Tea',
      description: 'A warming blend of lemongrass and ginger root. Perfect for cold weather, this immunity-boosting tea soothes sore throats and aids digestion. Made from sun-dried herbs.',
      shortDescription: 'Warming lemongrass ginger tea for immunity and digestion.',
      categoryName: 'Herbal Tea',
      price: 329,
      comparePrice: 449,
      costPrice: 200,
      sku: 'BLM-HRT-005',
      stock: 60,
      lowStockThreshold: 10,
      images: [{ public_id: 'seed/herbal-tea/lemongrass-ginger', url: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=500&auto=format&fit=crop&q=60' }],
      weight: 100,
      unit: 'g',
      tags: ['lemongrass', 'ginger', 'immunity', 'warming'],
      isFeatured: true,
      isActive: true,
      isOrganic: true,
      ratings: 4.4,
      numReviews: 41,
      soldCount: 170,
      metaTitle: 'Lemongrass Ginger Tea - BloomHerbs',
      metaDescription: 'Warming lemongrass ginger blend tea for immunity and wellness.',
    },

    // Coffee
    {
      name: 'Arabica Coffee Beans',
      description: 'Single-origin Arabica coffee beans from the highlands. Medium roast with notes of chocolate and nuts. Perfect for drip coffee, pour-over, and French press brewing methods.',
      shortDescription: 'Single-origin Arabica beans with chocolate and nut notes.',
      categoryName: 'Coffee',
      price: 699,
      comparePrice: 899,
      costPrice: 450,
      sku: 'BLM-COF-001',
      stock: 80,
      lowStockThreshold: 15,
      images: [{ public_id: 'seed/coffee/arabica', url: 'https://images.unsplash.com/photo-1509042239860-f5502b9005c6?w=500&auto=format&fit=crop&q=60' }],
      weight: 500,
      unit: 'g',
      tags: ['arabica', 'single-origin', 'medium-roast', 'beans'],
      isFeatured: true,
      isActive: true,
      isOrganic: true,
      ratings: 4.9,
      numReviews: 203,
      soldCount: 850,
      metaTitle: 'Arabica Coffee Beans - BloomHerbs',
      metaDescription: 'Premium single-origin Arabica coffee beans with rich chocolate notes.',
    },
    {
      name: 'Robusta Dark Roast',
      description: 'Bold and intense Robusta dark roast coffee. Full-bodied with deep earthy flavors and a strong caffeine kick. Ideal for espresso and those who prefer a powerful cup.',
      shortDescription: 'Bold Robusta dark roast for intense espresso lovers.',
      categoryName: 'Coffee',
      price: 549,
      comparePrice: 749,
      costPrice: 320,
      sku: 'BLM-COF-002',
      stock: 95,
      lowStockThreshold: 20,
      images: [{ public_id: 'seed/coffee/robusta', url: 'https://images.unsplash.com/photo-1559525839-8d9c94e2aa9e?w=500&auto=format&fit=crop&q=60' }],
      weight: 500,
      unit: 'g',
      tags: ['robusta', 'dark-roast', 'espresso', 'bold'],
      isFeatured: false,
      isActive: true,
      isOrganic: false,
      ratings: 4.6,
      numReviews: 156,
      soldCount: 620,
      metaTitle: 'Robusta Dark Roast Coffee - BloomHerbs',
      metaDescription: 'Bold Robusta dark roast coffee beans for strong espresso.',
    },
    {
      name: 'Espresso Blend Powder',
      description: 'Expertly crafted espresso blend combining the best Arabica and Robusta beans. Rich crema, balanced acidity, and smooth finish. Pre-ground for convenience.',
      shortDescription: 'Rich crema espresso blend, pre-ground for convenience.',
      categoryName: 'Coffee',
      price: 449,
      comparePrice: 599,
      costPrice: 280,
      sku: 'BLM-COF-003',
      stock: 110,
      lowStockThreshold: 20,
      images: [{ public_id: 'seed/coffee/espresso', url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefda?w=500&auto=format&fit=crop&q=60' }],
      weight: 250,
      unit: 'g',
      tags: ['espresso', 'blend', 'pre-ground', 'crema'],
      isFeatured: true,
      isActive: true,
      isOrganic: false,
      ratings: 4.7,
      numReviews: 178,
      soldCount: 710,
      metaTitle: 'Espresso Blend Coffee Powder - BloomHerbs',
      metaDescription: 'Premium espresso blend coffee powder with rich crema.',
    },
    {
      name: 'Colombian Supremo Coffee',
      description: 'Grown in the rich volcanic soils of Colombia, Supremo grade beans offer a well-balanced cup with bright acidity, caramel sweetness, and a lingering finish.',
      shortDescription: 'Well-balanced Colombian Supremo with caramel sweetness.',
      categoryName: 'Coffee',
      price: 799,
      comparePrice: 999,
      costPrice: 520,
      sku: 'BLM-COF-004',
      stock: 55,
      lowStockThreshold: 10,
      images: [{ public_id: 'seed/coffee/colombian', url: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=500&auto=format&fit=crop&q=60' }],
      weight: 500,
      unit: 'g',
      tags: ['colombian', 'supremo', 'balanced', 'premium'],
      isFeatured: true,
      isActive: true,
      isOrganic: true,
      ratings: 4.8,
      numReviews: 134,
      soldCount: 540,
      metaTitle: 'Colombian Supremo Coffee Beans - BloomHerbs',
      metaDescription: 'Premium Colombian Supremo coffee beans with balanced flavor.',
    },
    {
      name: 'Ethiopian Yirgacheffe',
      description: 'Light roast single-origin beans from the Yirgacheffe region. Known for distinctive floral notes, bright citrus acidity, and a tea-like body. A true connoisseur\'s choice.',
      shortDescription: 'Floral and bright Ethiopian Yirgacheffe light roast.',
      categoryName: 'Coffee',
      price: 899,
      comparePrice: 1099,
      costPrice: 600,
      sku: 'BLM-COF-005',
      stock: 40,
      lowStockThreshold: 8,
      images: [{ public_id: 'seed/coffee/yirgacheffe', url: 'https://images.unsplash.com/photo-1587734195341-6a9f470d4b07?w=500&auto=format&fit=crop&q=60' }],
      weight: 250,
      unit: 'g',
      tags: ['ethiopian', 'yirgacheffe', 'light-roast', 'floral'],
      isFeatured: false,
      isActive: true,
      isOrganic: true,
      ratings: 4.9,
      numReviews: 98,
      soldCount: 380,
      metaTitle: 'Ethiopian Yirgacheffe Coffee - BloomHerbs',
      metaDescription: 'Light roast Ethiopian Yirgacheffe with floral and citrus notes.',
    },

    // Pepper
    {
      name: 'Malabar Black Peppercorns',
      description: 'Hand-picked Malabar black peppercorns from the Western Ghats. Intensely aromatic with a sharp, hot flavor. Essential for Indian cooking and global cuisines.',
      shortDescription: 'Hand-picked Malabar black peppercorns, intense and aromatic.',
      categoryName: 'Pepper',
      price: 199,
      comparePrice: 299,
      costPrice: 110,
      sku: 'BLM-PEP-001',
      stock: 150,
      lowStockThreshold: 25,
      images: [{ public_id: 'seed/pepper/malabar-black', url: 'https://images.unsplash.com/photo-1596040033227-a4c3f64d7a4f?w=500&auto=format&fit=crop&q=60' }],
      weight: 100,
      unit: 'g',
      tags: ['black-pepper', 'malabar', 'whole', 'aromatic'],
      isFeatured: true,
      isActive: true,
      isOrganic: true,
      ratings: 4.7,
      numReviews: 112,
      soldCount: 480,
      metaTitle: 'Malabar Black Peppercorns - BloomHerbs',
      metaDescription: 'Premium hand-picked Malabar black peppercorns.',
    },
    {
      name: 'White Peppercorns',
      description: 'Milder and earthier than black pepper, these white peppercorns are perfect for light-colored dishes. Sun-dried and carefully sorted for uniform size.',
      shortDescription: 'Milder earthy white peppercorns for refined cooking.',
      categoryName: 'Pepper',
      price: 249,
      comparePrice: 349,
      costPrice: 150,
      sku: 'BLM-PEP-002',
      stock: 130,
      lowStockThreshold: 20,
      images: [{ public_id: 'seed/pepper/white', url: 'https://images.unsplash.com/photo-1604335399105-e0b86a9a7fd4?w=500&auto=format&fit=crop&q=60' }],
      weight: 100,
      unit: 'g',
      tags: ['white-pepper', 'mild', 'earthy', 'whole'],
      isFeatured: false,
      isActive: true,
      isOrganic: true,
      ratings: 4.5,
      numReviews: 76,
      soldCount: 310,
      metaTitle: 'White Peppercorns - BloomHerbs',
      metaDescription: 'Milder white peppercorns for light-colored and refined dishes.',
    },
    {
      name: 'Green Peppercorns',
      description: 'Fresh-tasting green peppercorns with a milder heat and herbaceous flavor. Excellent for pickling, sauces, and pepper steak. Harvested at peak maturity.',
      shortDescription: 'Fresh green peppercorns with mild heat and herbaceous flavor.',
      categoryName: 'Pepper',
      price: 229,
      comparePrice: 329,
      costPrice: 130,
      sku: 'BLM-PEP-003',
      stock: 100,
      lowStockThreshold: 15,
      images: [{ public_id: 'seed/pepper/green', url: 'https://images.unsplash.com/photo-1530595478534-79c1a7e7c4ab?w=500&auto=format&fit=crop&q=60' }],
      weight: 100,
      unit: 'g',
      tags: ['green-pepper', 'fresh', 'mild', 'pickling'],
      isFeatured: false,
      isActive: true,
      isOrganic: true,
      ratings: 4.4,
      numReviews: 45,
      soldCount: 180,
      metaTitle: 'Green Peppercorns - BloomHerbs',
      metaDescription: 'Fresh green peppercorns with a mild and herbaceous taste.',
    },
    {
      name: 'Cayenne Pepper Powder',
      description: 'Fiery cayenne pepper powder made from sun-dried red chilies. High heat level perfect for adding spice to curries, sauces, and beverages. Rich in capsaicin.',
      shortDescription: 'Fiery cayenne pepper powder for bold heat.',
      categoryName: 'Pepper',
      price: 149,
      comparePrice: 199,
      costPrice: 80,
      sku: 'BLM-PEP-004',
      stock: 180,
      lowStockThreshold: 30,
      images: [{ public_id: 'seed/pepper/cayenne', url: 'https://images.unsplash.com/photo-1582686218192-f844240d4559?w=500&auto=format&fit=crop&q=60' }],
      weight: 50,
      unit: 'g',
      tags: ['cayenne', 'chili', 'hot', 'spicy'],
      isFeatured: false,
      isActive: true,
      isOrganic: true,
      ratings: 4.6,
      numReviews: 91,
      soldCount: 390,
      metaTitle: 'Cayenne Pepper Powder - BloomHerbs',
      metaDescription: 'Fiery cayenne pepper powder for bold and spicy dishes.',
    },
    {
      name: 'Smoked Black Pepper',
      description: 'Oak-smoked black peppercorns with a deep, smoky aroma. Adds complexity to grilled meats, stews, and barbecue dishes. A gourmet twist on a classic spice.',
      shortDescription: 'Oak-smoked black pepper with deep smoky aroma.',
      categoryName: 'Pepper',
      price: 279,
      comparePrice: 379,
      costPrice: 160,
      sku: 'BLM-PEP-005',
      stock: 85,
      lowStockThreshold: 12,
      images: [{ public_id: 'seed/pepper/smoked', url: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=500&auto=format&fit=crop&q=60' }],
      weight: 100,
      unit: 'g',
      tags: ['smoked', 'black-pepper', 'gourmet', 'barbecue'],
      isFeatured: true,
      isActive: true,
      isOrganic: false,
      ratings: 4.3,
      numReviews: 38,
      soldCount: 145,
      metaTitle: 'Smoked Black Pepper - BloomHerbs',
      metaDescription: 'Oak-smoked black peppercorns with rich smoky flavor.',
    },

    // Spices
    {
      name: 'Ceylon Cinnamon Sticks',
      description: 'True Ceylon cinnamon from Sri Lanka, known as the "true cinnamon." Delicate, sweet, and complex flavor with multiple health benefits. Perfect for baking and beverages.',
      shortDescription: 'True Ceylon cinnamon sticks with delicate sweet flavor.',
      categoryName: 'Spices',
      price: 179,
      comparePrice: 249,
      costPrice: 100,
      sku: 'BLM-SPI-001',
      stock: 140,
      lowStockThreshold: 20,
      images: [{ public_id: 'seed/spices/cinnamon', url: 'https://images.unsplash.com/photo-1587132137056-bfbf0166836e?w=500&auto=format&fit=crop&q=60' }],
      weight: 50,
      unit: 'g',
      tags: ['cinnamon', 'ceylon', 'true-cinnamon', 'baking'],
      isFeatured: true,
      isActive: true,
      isOrganic: true,
      ratings: 4.8,
      numReviews: 167,
      soldCount: 620,
      metaTitle: 'Ceylon Cinnamon Sticks - BloomHerbs',
      metaDescription: 'Premium Ceylon cinnamon sticks, the true cinnamon from Sri Lanka.',
    },
    {
      name: 'Green Cardamom Pods',
      description: 'Fragrant green cardamom pods from the misty hills of Kerala. Intensely aromatic with sweet, floral notes. Essential for Indian desserts, chai, and rice dishes.',
      shortDescription: 'Fragrant green cardamom pods from Kerala hills.',
      categoryName: 'Spices',
      price: 299,
      comparePrice: 399,
      costPrice: 180,
      sku: 'BLM-SPI-002',
      stock: 100,
      lowStockThreshold: 15,
      images: [{ public_id: 'seed/spices/cardamom', url: 'https://images.unsplash.com/photo-1599909533621-9ab40b250ca5?w=500&auto=format&fit=crop&q=60' }],
      weight: 50,
      unit: 'g',
      tags: ['cardamom', 'elaichi', 'aromatic', 'kerala'],
      isFeatured: true,
      isActive: true,
      isOrganic: true,
      ratings: 4.7,
      numReviews: 143,
      soldCount: 580,
      metaTitle: 'Green Cardamom Pods - BloomHerbs',
      metaDescription: 'Fragrant green cardamom pods for chai and desserts.',
    },
    {
      name: 'Whole Cloves',
      description: 'Premium whole cloves sourced from the Nilgiri hills. Intensely aromatic with warm, sweet, and slightly bitter notes. Perfect for garam masala, baking, and mulled beverages.',
      shortDescription: 'Premium whole cloves with warm sweet aromatic notes.',
      categoryName: 'Spices',
      price: 199,
      comparePrice: 279,
      costPrice: 110,
      sku: 'BLM-SPI-003',
      stock: 120,
      lowStockThreshold: 20,
      images: [{ public_id: 'seed/spices/cloves', url: 'https://images.unsplash.com/photo-1599946347371-68eb71b16afc?w=500&auto=format&fit=crop&q=60' }],
      weight: 50,
      unit: 'g',
      tags: ['cloves', 'aromatic', 'warm', 'baking'],
      isFeatured: false,
      isActive: true,
      isOrganic: true,
      ratings: 4.6,
      numReviews: 89,
      soldCount: 360,
      metaTitle: 'Whole Cloves - BloomHerbs',
      metaDescription: 'Premium whole cloves with intense aromatic warmth.',
    },
    {
      name: 'Turmeric Powder',
      description: 'Pure ground turmeric from organic farms in Salem. High curcumin content with vibrant golden color. Anti-inflammatory properties make this a kitchen superfood.',
      shortDescription: 'Pure organic turmeric powder with high curcumin content.',
      categoryName: 'Spices',
      price: 129,
      comparePrice: 179,
      costPrice: 70,
      sku: 'BLM-SPI-004',
      stock: 200,
      lowStockThreshold: 30,
      images: [{ public_id: 'seed/spices/turmeric', url: 'https://images.unsplash.com/photo-1615485500634-4d68a1947553?w=500&auto=format&fit=crop&q=60' }],
      weight: 100,
      unit: 'g',
      tags: ['turmeric', 'haldi', 'organic', 'anti-inflammatory'],
      isFeatured: true,
      isActive: true,
      isOrganic: true,
      ratings: 4.5,
      numReviews: 198,
      soldCount: 920,
      metaTitle: 'Turmeric Powder - BloomHerbs',
      metaDescription: 'Pure organic turmeric powder with high curcumin content.',
    },
    {
      name: 'Kashmiri Red Chili Powder',
      description: 'Vibrant Kashmiri red chili powder known for its bright color and moderate heat. Perfect for tandoori dishes, curries, and adding beautiful color to food.',
      shortDescription: 'Vibrant Kashmiri red chili with moderate heat and color.',
      categoryName: 'Spices',
      price: 159,
      comparePrice: 229,
      costPrice: 85,
      sku: 'BLM-SPI-005',
      stock: 160,
      lowStockThreshold: 25,
      images: [{ public_id: 'seed/spices/chili', url: 'https://images.unsplash.com/photo-1583324113626-70df0f3dea16?w=500&auto=format&fit=crop&q=60' }],
      weight: 100,
      unit: 'g',
      tags: ['chili', 'kashmiri', 'red', 'moderate-heat'],
      isFeatured: false,
      isActive: true,
      isOrganic: true,
      ratings: 4.7,
      numReviews: 124,
      soldCount: 550,
      metaTitle: 'Kashmiri Red Chili Powder - BloomHerbs',
      metaDescription: 'Vibrant Kashmiri red chili powder for color and moderate heat.',
    },

    // Honey
    {
      name: 'Raw Wildflower Honey',
      description: 'Unprocessed, unfiltered wildflower honey collected from diverse meadow flowers. Thick, creamy texture with complex floral notes. Contains natural pollen and enzymes.',
      shortDescription: 'Unfiltered raw wildflower honey with natural pollen.',
      categoryName: 'Honey',
      price: 449,
      comparePrice: 599,
      costPrice: 280,
      sku: 'BLM-HON-001',
      stock: 70,
      lowStockThreshold: 10,
      images: [{ public_id: 'seed/honey/wildflower', url: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&auto=format&fit=crop&q=60' }],
      weight: 500,
      unit: 'g',
      tags: ['honey', 'raw', 'wildflower', 'unfiltered'],
      isFeatured: true,
      isActive: true,
      isOrganic: true,
      ratings: 4.9,
      numReviews: 215,
      soldCount: 780,
      metaTitle: 'Raw Wildflower Honey - BloomHerbs',
      metaDescription: 'Pure raw wildflower honey, unfiltered with natural pollen.',
    },
    {
      name: 'Manuka Honey UMF 10+',
      description: 'Premium New Zealand Manuka honey with UMF 10+ certification. Renowned for its unique antibacterial properties. Smooth, thick texture with a distinctive earthy flavor.',
      shortDescription: 'Premium UMF 10+ Manuka honey from New Zealand.',
      categoryName: 'Honey',
      price: 1299,
      comparePrice: 1599,
      costPrice: 850,
      sku: 'BLM-HON-002',
      stock: 30,
      lowStockThreshold: 5,
      images: [{ public_id: 'seed/honey/manuka', url: 'https://images.unsplash.com/photo-1542528180-a1208c5169a5?w=500&auto=format&fit=crop&q=60' }],
      weight: 250,
      unit: 'g',
      tags: ['manuka', 'umf10+', 'new-zealand', 'premium'],
      isFeatured: true,
      isActive: true,
      isOrganic: false,
      ratings: 4.8,
      numReviews: 156,
      soldCount: 290,
      metaTitle: 'Manuka Honey UMF 10+ - BloomHerbs',
      metaDescription: 'Premium UMF 10+ Manuka honey with unique antibacterial properties.',
    },
    {
      name: 'Acacia Honey',
      description: 'Light and sweet Acacia honey with a delicate floral aroma. Slow to crystallize, making it a favorite for dressings, teas, and drizzling over yogurt or toast.',
      shortDescription: 'Light and sweet Acacia honey with delicate floral aroma.',
      categoryName: 'Honey',
      price: 549,
      comparePrice: 699,
      costPrice: 340,
      sku: 'BLM-HON-003',
      stock: 65,
      lowStockThreshold: 10,
      images: [{ public_id: 'seed/honey/acacia', url: 'https://images.unsplash.com/photo-1471943295830-7f1b9ab5a107?w=500&auto=format&fit=crop&q=60' }],
      weight: 500,
      unit: 'g',
      tags: ['acacia', 'light', 'sweet', 'floral'],
      isFeatured: false,
      isActive: true,
      isOrganic: true,
      ratings: 4.6,
      numReviews: 98,
      soldCount: 410,
      metaTitle: 'Acacia Honey - BloomHerbs',
      metaDescription: 'Pure light and sweet Acacia honey with delicate floral notes.',
    },
    {
      name: 'Forest Honey',
      description: 'Dark, rich forest honey harvested from deep forest apiaries. Complex, malty flavor with hints of caramel and wood. Perfect for baking, glazes, and robust dishes.',
      shortDescription: 'Dark rich forest honey with complex malty flavor.',
      categoryName: 'Honey',
      price: 399,
      comparePrice: 549,
      costPrice: 240,
      sku: 'BLM-HON-004',
      stock: 80,
      lowStockThreshold: 12,
      images: [{ public_id: 'seed/honey/forest', url: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=500&auto=format&fit=crop&q=60' }],
      weight: 500,
      unit: 'g',
      tags: ['forest', 'dark', 'malty', 'rich'],
      isFeatured: false,
      isActive: true,
      isOrganic: true,
      ratings: 4.5,
      numReviews: 72,
      soldCount: 300,
      metaTitle: 'Forest Honey - BloomHerbs',
      metaDescription: 'Dark and rich forest honey with complex malty flavor.',
    },
    {
      name: 'Ginger Infused Honey',
      description: 'Raw honey infused with fresh ginger root for a warming, zesty treat. Perfect for soothing sore throats, adding to tea, or taking by the spoonful when feeling under the weather.',
      shortDescription: 'Raw honey infused with fresh ginger for warmth and wellness.',
      categoryName: 'Honey',
      price: 349,
      comparePrice: 449,
      costPrice: 210,
      sku: 'BLM-HON-005',
      stock: 90,
      lowStockThreshold: 15,
      images: [{ public_id: 'seed/honey/ginger', url: 'https://images.unsplash.com/photo-1615478503562-ec2d8ff4d1dc?w=500&auto=format&fit=crop&q=60' }],
      weight: 250,
      unit: 'g',
      tags: ['honey', 'ginger', 'infused', 'soothing'],
      isFeatured: true,
      isActive: true,
      isOrganic: true,
      ratings: 4.4,
      numReviews: 63,
      soldCount: 260,
      metaTitle: 'Ginger Infused Honey - BloomHerbs',
      metaDescription: 'Raw honey infused with fresh ginger for wellness and warmth.',
    },

    // Extra products to exceed minimum
    {
      name: 'Lemon Balm Tea',
      description: 'Calming lemon balm tea with a subtle citrus flavor. Known for reducing stress and anxiety while supporting cognitive function. Caffeine-free and naturally sweet.',
      shortDescription: 'Calming lemon balm tea with subtle citrus flavor.',
      categoryName: 'Herbal Tea',
      price: 269,
      comparePrice: 369,
      costPrice: 160,
      sku: 'BLM-HRT-006',
      stock: 75,
      lowStockThreshold: 12,
      images: [{ public_id: 'seed/herbal-tea/lemon-balm', url: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=60' }],
      weight: 80,
      unit: 'g',
      tags: ['lemon-balm', 'calming', 'caffeine-free', 'citrus'],
      isFeatured: false,
      isActive: true,
      isOrganic: true,
      ratings: 4.3,
      numReviews: 35,
      soldCount: 140,
      metaTitle: 'Lemon Balm Tea - BloomHerbs',
      metaDescription: 'Calming lemon balm tea for stress relief and relaxation.',
    },
    {
      name: 'Instant Coffee Powder',
      description: 'Convenient instant coffee powder made from premium Arabica beans. Dissolves instantly for a smooth, rich cup. Perfect for busy mornings and travel.',
      shortDescription: 'Convenient instant coffee from premium Arabica beans.',
      categoryName: 'Coffee',
      price: 299,
      comparePrice: 399,
      costPrice: 170,
      sku: 'BLM-COF-006',
      stock: 140,
      lowStockThreshold: 20,
      images: [{ public_id: 'seed/coffee/instant', url: 'https://images.unsplash.com/photo-1507133750069-b736403d33b2?w=500&auto=format&fit=crop&q=60' }],
      weight: 100,
      unit: 'g',
      tags: ['instant', 'arabica', 'convenient', 'smooth'],
      isFeatured: false,
      isActive: true,
      isOrganic: false,
      ratings: 4.2,
      numReviews: 58,
      soldCount: 420,
      metaTitle: 'Instant Coffee Powder - BloomHerbs',
      metaDescription: 'Premium instant coffee powder made from Arabica beans.',
    },
  ];

  for (const prod of products) {
    const cat = categories.find((c) => c.name === prod.categoryName);
    if (!cat) {
      console.log(`  ! Skipping ${prod.name}: category not found`);
      continue;
    }

    const existing = await Product.findOne({ sku: prod.sku });
    if (!existing) {
      const { categoryName, ...productData } = prod;
      const product = await Product.create({
        ...productData,
        category: cat._id,
        slug: slugify(prod.name, { lower: true }),
      });
      console.log(`  ✓ Product created: ${product.name}`);
    } else {
      console.log(`  - Product exists: ${prod.name}`);
    }
  }
};

const seedCoupons = async () => {
  const coupons = [
    {
      code: 'BLOOM10',
      description: '10% off on orders above ₹500',
      discountType: 'percentage',
      discountValue: 10,
      minOrderAmount: 500,
      maxDiscountAmount: 200,
      usageLimit: 1000,
      usedCount: 0,
      usedBy: [],
      isActive: true,
      expiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    },
    {
      code: 'WELCOME20',
      description: '20% off on first order above ₹1000',
      discountType: 'percentage',
      discountValue: 20,
      minOrderAmount: 1000,
      maxDiscountAmount: 500,
      usageLimit: 500,
      usedCount: 0,
      usedBy: [],
      isActive: true,
      expiresAt: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    },
    {
      code: 'FLAT100',
      description: 'Flat ₹100 off on orders above ₹800',
      discountType: 'fixed',
      discountValue: 100,
      minOrderAmount: 800,
      usageLimit: 200,
      usedCount: 0,
      usedBy: [],
      isActive: true,
      expiresAt: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    },
  ];

  for (const coupon of coupons) {
    const existing = await Coupon.findOne({ code: coupon.code });
    if (!existing) {
      await Coupon.create(coupon);
      console.log(`  ✓ Coupon created: ${coupon.code}`);
    } else {
      console.log(`  - Coupon exists: ${coupon.code}`);
    }
  }
};

const seedAdminUser = async () => {
  const existingAdmin = await User.findOne({ email: 'admin@bloomherbs.com' });
  if (!existingAdmin) {
    const admin = await User.create({
      name: 'Admin User',
      email: 'admin@bloomherbs.com',
      password: 'admin123',
      phone: '9999999999',
      role: 'admin',
      isActive: true,
      isEmailVerified: true,
    });
    console.log(`  ✓ Admin user created: ${admin.email}`);
  } else {
    console.log(`  - Admin user exists: admin@bloomherbs.com`);
  }
};

const seedData = async () => {
  try {
    await connectDB();

    console.log('\n🌱 Starting seed...\n');

    console.log('📂 Seeding categories...');
    const categories = await seedCategories();

    console.log('\n📦 Seeding products...');
    await seedProducts(categories);

    console.log('\n🎫 Seeding coupons...');
    await seedCoupons();

    console.log('\n👤 Seeding admin user...');
    await seedAdminUser();

    console.log('\n✅ Seed completed successfully!\n');
    console.log('Default admin login: admin@bloomherbs.com / admin123\n');
  } catch (error) {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
    console.log('👋 MongoDB connection closed');
    process.exit(0);
  }
};

seedData();
